name: Build and test Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-on-ubuntu:
    name: Build and test on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

    - name: Set up Go
      uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v3.2.0
      with:
        go-version-file: './go.mod'

    - name: Build
      run: CGO_ENABLED=0 GOARCH=$TARGETARCH GOOS=$TARGETOS go build -v -a -o lagoon ./cmd

    - name: Test
      run: go test -v ./...